# Checkov Configuration for Terraform Security Scanning
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

# Framework to scan
framework:
  - terraform

# Output format
output: cli

# Fail on severity
compact: false
quiet: false

# Enable specific checks (AWS best practices)
check:
  # ECS Security
  - CKV_AWS_8    # Ensure ECS task definition has memory limit
  - CKV_AWS_97   # Ensure ECS task definition encrypts data in transit
  - CKV_AWS_249  # Ensure ECS task definition defines a user

  # IAM Security
  - CKV_AWS_60   # Ensure IAM role policies do not grant excessive permissions
  - CKV_AWS_61   # Ensure AWS IAM policy does not grant full permissions
  - CKV_AWS_62   # Ensure no IAM policies allow full "*:*" permissions
  - CKV_AWS_63   # Ensure IAM policies are attached only to groups or roles
  - CKV_AWS_107  # Ensure IAM policies does not allow credentials exposure
  - CKV_AWS_108  # Ensure IAM policies does not allow data exfiltration
  - CKV_AWS_109  # Ensure IAM policies does not allow permissions management
  - CKV_AWS_110  # Ensure IAM policies does not allow privilege escalation
  - CKV_AWS_111  # Ensure IAM policies does not allow write access without constraints

  # VPC & Network Security
  - CKV_AWS_23   # Ensure security groups have descriptions
  - CKV_AWS_24   # Ensure no security groups allow ingress from 0.0.0.0/0 to port 22
  - CKV_AWS_25   # Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389
  - CKV_AWS_260  # Ensure no security groups allow ingress from 0.0.0.0/0 to port 80
  - CKV_AWS_277  # Ensure no security groups allow ingress from 0.0.0.0/0 to port 3306
  - CKV_AWS_130  # Ensure VPC subnets do not assign public IP by default

  # CloudWatch & Logging
  - CKV_AWS_158  # Ensure CloudWatch log groups are encrypted at rest
  - CKV_AWS_338  # Ensure CloudWatch log groups retains logs for at least 1 year

  # ELB/ALB Security
  - CKV_AWS_91   # Ensure ALB has access logging enabled
  - CKV_AWS_103  # Ensure that ALB is using TLS 1.2
  - CKV_AWS_131  # Ensure ALB drops invalid HTTP headers
  - CKV_AWS_150  # Ensure that ALB is configured with defensive or strictest desync mitigation mode

  # S3 Security (for Terraform state)
  - CKV_AWS_18   # Ensure S3 bucket has access logging enabled
  - CKV_AWS_19   # Ensure S3 bucket has server-side encryption enabled
  - CKV_AWS_21   # Ensure S3 bucket has versioning enabled
  - CKV_AWS_144  # Ensure S3 bucket has cross-region replication enabled
  - CKV_AWS_145  # Ensure S3 bucket has KMS encryption enabled

  # ECR Security
  - CKV_AWS_136  # Ensure ECR repository has image scanning enabled
  - CKV_AWS_163  # Ensure ECR repository has KMS encryption enabled

# Skip specific checks (with justification)
skip-check:
  # We're using HTTP for demo purposes (not production)
  - CKV_AWS_2    # ALB HTTPS listener (demo uses HTTP)
  - CKV_AWS_103  # ALB TLS 1.2 (demo uses HTTP)

  # CloudWatch log encryption - adding later for cost optimization
  - CKV_AWS_338  # 1-year log retention (too long for demo dev environment)

  # Not applicable to this demo
  - CKV_AWS_40   # IAM password policy (we're not using IAM users)
  - CKV_AWS_144  # S3 cross-region replication (single region demo)

  # False positives for demo
  - CKV_AWS_260  # Port 80 from 0.0.0.0/0 (we need this for public demo ALB)

  # Optional enhancements (not required for demo)
  - CKV_AWS_91   # ALB access logging (adds cost, not needed for demo)

# Severity levels to fail on
# Options: CRITICAL, HIGH, MEDIUM, LOW
# For production, use: soft-fail: false
# For demo/development, we'll be lenient
soft-fail: true

# Directories to exclude
skip-path:
  - .terraform/
  - .terragrunt-cache/
  - terraform/policies/  # Don't scan policy files themselves

# Additional settings
download-external-modules: false
evaluate-variables: true
